import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  /**
   * Workspace packages ship raw TypeScript (`main` points at `src/index.ts`) rather than a build
   * step, so Next has to compile them itself. Without this they arrive as untranspiled TS and the
   * build fails on the first type annotation.
   */
  transpilePackages: ["@tricity/domain", "@tricity/geo"],

  images: {
    /**
     * Sample listing photos are SVGs generated by our own /api/placeholder route. Next blocks SVG
     * optimization by default because a hostile SVG can carry script — not a concern for
     * first-party generated markup, and the CSP below sandboxes them regardless.
     *
     * When real photos land, add the media CDN host to `remotePatterns` here. Real listing photos
     * are JPEGs, so this flag can be dropped once the placeholder route is retired.
     */
    dangerouslyAllowSVG: true,
    contentDispositionType: "attachment",
    contentSecurityPolicy: "default-src 'self'; script-src 'none'; sandbox;",

    // remotePatterns: [{ protocol: "https", hostname: "<media-cdn>" }],
  },
};

export default nextConfig;
