import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  /**
   * Workspace packages ship raw TypeScript (`main` points at `src/index.ts`) rather than a build
   * step, so Next has to compile them itself. Without this they arrive as untranspiled TS and the
   * build fails on the first type annotation.
   */
  /*
   * ⚠️ EVERY workspace package the app imports must be listed. These ship raw TypeScript and are
   * compiled by the consumer, so an omitted one is not a build error — it resolves through the
   * node_modules workspace symlink and happens to work until a clean install or a bundler change
   * says otherwise. `@tricity/contracts` was missing here while `api-provider.ts` imported a
   * VALUE from it, which is exactly that latent failure.
   */
  transpilePackages: ["@tricity/contracts", "@tricity/domain", "@tricity/geo"],

  images: {
    /**
     * Sample listing photos are SVGs generated by our own /api/placeholder route. Next blocks SVG
     * optimization by default because a hostile SVG can carry script — not a concern for
     * first-party generated markup, and the CSP below sandboxes them regardless.
     *
     * When real photos land, add the media CDN host to `remotePatterns` here. Real listing photos
     * are JPEGs, so this flag can be dropped once the placeholder route is retired.
     */
    dangerouslyAllowSVG: true,
    contentDispositionType: "attachment",
    contentSecurityPolicy: "default-src 'self'; script-src 'none'; sandbox;",

    /*
     * ⚠️ INTENTIONALLY EMPTY. Listing photos do NOT go through next/image.
     *
     * The API already emits exactly-sized WebP variants, so the optimizer would re-encode work
     * already done — and pointing it at the media host couples this config to an environment
     * variable whose mismatch fails SILENTLY: `400 "url" parameter is not allowed`, page renders
     * fine, every photo blank. See components/listings/ListingImage.tsx.
     *
     * Add a host here only for images that genuinely need optimizing (editorial photography,
     * an agent headshot), never for listing media.
     */
  },
};

export default nextConfig;
