import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    /**
     * Sample listing photos are SVGs generated by our own /api/placeholder route. Next blocks SVG
     * optimization by default because a hostile SVG can carry script — not a concern for
     * first-party generated markup, and the CSP below sandboxes them regardless.
     *
     * When the MLS feed lands, add the CDN host to `remotePatterns` here. Real listing photos are
     * JPEGs, so this flag can be dropped once the placeholder route is retired.
     */
    dangerouslyAllowSVG: true,
    contentDispositionType: "attachment",
    contentSecurityPolicy: "default-src 'self'; script-src 'none'; sandbox;",

    // remotePatterns: [{ protocol: "https", hostname: "<mls-photo-cdn>" }],
  },
};

export default nextConfig;
